[package]
name = "html5ever_nif"
version = "0.1.0"
authors = ["HansiHE <hansihe@hansihe.com>"]

[lib]
name = "html5ever_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "^0.21"
rustler_codegen = "^0.21"
#rustler = { path = "../../../Rustler/" }
#rustler_codegen = { path = "../../../Rustler/rustler_codegen/" }

html5ever = "0.24.0"
markup5ever = "0.10.0"

tendril = "0.4"
lazy_static = "1.4"
scoped-pool = "1.0"
